name: lookatfy-appv1
services:
  - name: web
    environment_slug: node-js
    source_dir: .
    instance_size_slug: basic-xxs
    instance_count: 1
    build_command: npm ci && npm run build
    run_command: npm run start -- -p $PORT
    routes:
      - path: /
    envs:
      - key: NEXT_PUBLIC_SUPABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: DAILY_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: SUPABASE_SERVICE_ROLE_KEY
        scope: RUN_TIME
        type: SECRET
